---

- name: Copy tools
  copy:
    src: files/
    dest: "/home/{{ansible_user}}/{{working_dir}}/tools/"
    mode: preserve

- name: Pass environment variables
  template:
    src: templates/env_vars.sh.j2
    dest: "/home/{{ansible_user}}/{{working_dir}}/env_vars.sh"

# Vanilla Measurement

- name: Include random response test
  include_tasks: responses.yml
  vars:
    - pcap_file: queries-ipv4rand.pcap
    - test_name: "random-response-{{server}}"
  when: zones=="random"

- name: Include real response test
  include_tasks: responses.yml
  vars:
    - pcap_file: queries-ipv4real.pcap
    - test_name: "real-response-{{server}}"
  when: zones=="real"

# Response times

- name: Include random response times
  include_tasks: times.yml
  vars:
    - test_name: "random-times-{{server}}"
    - zonelist: zonelist
  when: zones=="random"

- name: Include random response times
  include_tasks: times.yml
  vars:
    - test_name: "real-times-{{server}}"
    - zonelist: parsed_zonelist
  when: zones=="real"

# Controlled failure
- name: Include Controlled system failures
  include_tasks: shutdowns.yml
  vars:
    - test_name: "random-segfault-{{server}}"
    - zonelist: zonelist
  when: zones=="random"

- name: Include Controlled system failures
  include_tasks: shutdowns.yml
  vars:
    - test_name: "real-segfault-{{server}}"
    - zonelist: parsed_zonelist
  when: zones=="real"

  # Close Future
- name: Do test with memory measurement
  debug: msg="Implement me!"