---

- name: Copy tools
  copy:
    src: files/
    dest: "/home/{{ansible_user}}/{{working_dir}}/tools/"
    mode: preserve

- name: Pass environment variables
  template:
    src: templates/env_vars.sh.j2
    dest: "/home/{{ansible_user}}/{{working_dir}}/env_vars.sh"

# Vanilla Measurement

- name: Include random response test
  include_tasks: responses.yml
  vars:
    - pcap_file: queries-ipv4rand.pcap
    - test_name: "random-response-{{server}}"

- name: Include real response test
  include_tasks: responses.yml
  vars:
    - pcap_file: queries-ipv4real.pcap
    - test_name: "real-response-{{server}}"

# Close Future
- name: Do test with controlled system failures
  debug: msg="Implement me!"

- name: Do test with memory measurement
  debug: msg="Implement me!"

- name: Do test with avg time response using dig
  debug: msg="Implement me!"