---

- name: Copy tools
  copy:
    src: files/
    dest: "/home/{{ansible_user}}/{{working_dir}}/tools/"
    mode: preserve

# Vanilla Measurement

- name: Include random response test
  include_tasks: responses.yml
  vars:
    - pcap_file: queries-ipv4rand.pcap
    - test_name: random-response

- name: Include real response test
  include_tasks: responses.yml
  vars:
    - pcap_file: queries-ipv4real.pcap
    - test_name: real-response

# Close Future
- name: Do test with controlled system failures
  debug: msg="Implement me!"

- name: Do test with memory measurement
  debug: msg="Implement me!"

- name: Do test with avg time response using dig
  debug: msg="Implement me!"