---

# Define the following variables when including
# pcap_file
# test_name

- name: Do tcpreplay from requester with different RR
  script: 'files/measure.sh {{item}} {{pcap_file}} ./results/wireshark-{{test_name}}.log'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  with_sequence: "start={{pps_floor}} stride={{pps_step}} end={{shutdown_pps_top if shutdown_pps_top is defined else pps_ceil }}"

- name: Recover results and clean
  script: 'files/clean_and_recover.sh results-{{test_name}}'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"

- name: Recover results from Working directory
  fetch:
    src: "/home/{{ansible_user}}/{{working_dir}}/results/{{item}}"
    dest: "results/{{test_name}}/{{item}}"
    flat: yes
  loop:
    - "results-{{test_name}}.{{server_A}}.tar.gz"
    - "results-{{test_name}}.{{server_B}}.tar.gz"
    - "results-{{test_name}}.{{server_C}}.tar.gz"
    - "results-{{test_name}}-mem.{{server_A}}.tar.gz"
    - "results-{{test_name}}-mem.{{server_B}}.tar.gz"
    - "results-{{test_name}}-mem.{{server_C}}.tar.gz"
    - "results-{{test_name}}-cpu.{{server_A}}.tar.gz"
    - "results-{{test_name}}-cpu.{{server_B}}.tar.gz"
    - "results-{{test_name}}-cpu.{{server_C}}.tar.gz"
    - "results-{{test_name}}-load.{{server_A}}.tar.gz"
    - "results-{{test_name}}-load.{{server_B}}.tar.gz"
    - "results-{{test_name}}-load.{{server_C}}.tar.gz"
    - "wireshark-{{test_name}}.log"

- name: Remove file from requester
  file:
    state: absent
    path: "/home/{{ansible_user}}/{{working_dir}}/results/{{item}}"
  loop:
    - "results-{{test_name}}.{{server_A}}.tar.gz"  
    - "results-{{test_name}}.{{server_B}}.tar.gz"
    - "results-{{test_name}}.{{server_C}}.tar.gz"
    - "results-{{test_name}}-mem.{{server_A}}.tar.gz"  
    - "results-{{test_name}}-mem.{{server_B}}.tar.gz"
    - "results-{{test_name}}-mem.{{server_C}}.tar.gz"
    - "results-{{test_name}}-cpu.{{server_A}}.tar.gz"
    - "results-{{test_name}}-cpu.{{server_B}}.tar.gz"
    - "results-{{test_name}}-cpu.{{server_C}}.tar.gz"
    - "results-{{test_name}}-load.{{server_A}}.tar.gz"
    - "results-{{test_name}}-load.{{server_B}}.tar.gz"
    - "results-{{test_name}}-load.{{server_C}}.tar.gz"
    - "wireshark-{{test_name}}.log"