---

# Define the following variables when including
# pcap_file
# test_name
# 

- name: Do tcpreplay from requester with random RR
  command: './tools/measure.sh {{item}} {{pcap_file}} {{ansible_user}} "{{server_A}} {{server_B}} {{server_C}}" {{working_dir}} {{ansible_default_ipv4["interface"]}}'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  with_sequence: "start={{pps_floor}} stride={{pps_step}} end={{pps_ceil}}"

- name: Recover results and clean
  command: './tools/clean_and_recover.sh "{{server_A}} {{server_B}} {{server_C}}" {{working_dir}} results-{{test_name}} {{ansible_user}}'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"

- name: Recover results from Working directory
  fetch:
    src: "/home/{{ansible_user}}/{{working_dir}}/results-{{test_name}}.tar.gz"
    dest: "results/{{ansible_default_ipv4.address}}/results-{{test_name}}.tar.gz"
    flat: yes

- name: Remove file from requester
  file:
    state: absent
    path: "/home/{{ansible_user}}/{{working_dir}}/results-{{test_name}}.tar.gz"