---

- name: Start random server killer
  shell: "nohup ./tools/random_killer.sh {{server}} </dev/null >/dev/null 2>&1 &"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"

- name: Include responses tasks
  include_tasks: responses.yml
  vars:
    - shutdown_pps_top: "{{shutdown_ceil}}"

  # This might be unecessary
- name: Stop random server killer
  shell: "kill $(cat killer.pid)"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  ignore_errors: yes