---

# For each backend we must start and then populate
# the respective db

- name: Pass Custom Makefile
  template:
    src: templates/Makefile.j2
    dest: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/Makefile"

- name: Start server backend
  expect:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns"
    command: "make run_{{server}}"
    responses:
      (?i)password: "{{remote_playbook_password}}"

- name: Compile uploader and tools
  command: make build_cmd
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns"

- name: Check for populated.log
  stat:
    path: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/populated.log"
  register: populated

- name: Upload data folders (may take a while)
  command: './queryuploader -useZones true -datasetFolder ../../../data/{{item}} -clusterIPs "{{server_A}},{{server_B}},{{server_C}}" -db {{server}}'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/cmd/queryuploader"
  loop:
    - kvsZones
    - zones
  when: populated.stat.size is not defined

- name: Register operation
  shell: 
    cmd: cat "uploaded at $(date '+%Y%m%d-%H-%M')" > populated.log
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/"
  when: populated.stat.size is not defined