---

# For each backend we must start and then populate
# the respective db

- name: Pass Custom Makefile
  template:
    src: templates/Makefile.j2
    dest: "/home/{{ansible_user}}/{{working_dir}}/kvsDns/Makefile"

- name: Start server backend
  expect:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/kvsDns"
    command: "make run_{{server}}"
    responses:
      (?i)password: "{{remote_playbook_password}}"

- name: Compile uploader and tools
  command:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/kvsDns"
    argv:
      - make build_cmd

- name: Check for populated.log
  stat:
    path: "/home/{{ansible_user}}/{{working_dir}}/kvsDns/populated.log"
  register: populated

- name: Upload data folders (may take a while)
  command:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/kvsDns/cmd/queryuploader"
    argv: 
      - './queryuploader -useZones true -datasetFolder ../../../data/{{item.folder}} -clusterIPs "{{server_A}},{{server_B}},{{server_C}}" -db {{server}}'
  loop:
    - kvsZones
    - zones
  when: populated.stat.size is not defined

- name: Register operation
  command:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/kvsDns/"
    argv: 
      - cat "uploaded at $(date '+%Y%m%d-%H-%M')" > populated.log
  when: populated.stat.size is not defined