---

# Each server must start and then be populated
# either by zone files or direct API interaction

- name: Recover from master the server configurations
  copy: 
    src: "buffer/{{item}}"
    dest: "/home/{{ansible_user}}/{{working_dir}}/{{item}}"
  loop:
    - bind9.conf
    - knot2.conf
    - nsd4.conf

- name: Create zone extraction folders
  file:
    path: "/home/{{ansible_user}}/{{working_dir}}/data/{{item}}"
    state: directory
  loop:
    - "kvsZones"
    - "zones"

- name: Extract zones to data folder
  unarchive:
    dest: "/home/{{ansible_user}}/{{working_dir}}/data/{{item.folder}}/"
    src: "buffer/{{item.src}}"
    remote_src: no
  loop:
    - { src: 'kvsZones.tgz', folder: "kvsZones" }
    - { src: 'zones.tgz', folder: "zones" }
  
- name: Copy Script templates
  template:
    dest: "/home/{{ansible_user}}/{{working_dir}}/{{item.dest}}"
    src: "templates/{{item.src}}"
    mode: 0774  
  vars:
    - interface: "{{ ansible_facts | dict2items | selectattr('value.ipv4', 'defined') | selectattr('value.ipv4.address', 'equalto', ansible_default_ipv4.address) | first}}"
  loop:
    - { src: 'gather_stats.sh.j2', dest: "gather_stats.sh" }
    - { src: 'compute_rate.sh.j2', dest: "compute_rate.sh" }

- name: Start Bind9 server
  shell: "{{item}}"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  loop:
    - "bind9/bin/named/named -c bind9.conf -f -n {{ansible_processor_cores}} &> server.log &"
    - $! > server.pid
  when: server == "bind9"
  
- name: Start Knot2
  shell:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
    argv:
      - knot2/src/knotd -c knot2.conf &> server.log &
      - $! > server.pid #Capture pid
  when: server == "knot2"

- name: Start Nsd4
  shell: nsd4/nsd -c nsd4.conf -d &> server.log &
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "nsd4"

- name: Start KvsDns and populate
  include_tasks: populate.yml
  when: (orchestrate is defined) and (server != "bind9" and server != "knot2" and server != "nsd4")

- name: Start KvsDns client
  include_tasks: kvsDns.yml
  when: (server != "bind9" and server != "knot2" and server != "nsd4")
