---

# Each server must start and then be populated
# either by zone files or direct API interaction

- name: Make Folders
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "/home/{{ansible_user}}/{{working_dir}}/data"
    - "/home/{{ansible_user}}/{{working_dir}}/tools"
    - "/home/{{ansible_user}}/{{working_dir}}/results"

- name: Parse templates from master to servers
  template: 
    src: "buffer/{{item.src}}"
    dest: "/home/{{ansible_user}}/{{working_dir}}/{{item.dest}}"
  loop:
    - { src: 'bind9.conf.j2', dest: "bind9.conf" }
    - { src: 'knot2.conf.j2', dest: "knot2.conf" }
    - { src: 'nsd4.conf.j2', dest: "nsd4.conf" }
    - { src: 'bind9r.conf.j2', dest: "bind9r.conf" }
    - { src: 'knot2r.conf.j2', dest: "knot2r.conf" }
    - { src: 'nsd4r.conf.j2', dest: "nsd4r.conf" }

- name: Copy zonelists
  copy:
    dest: "buffer/{{item}}"
    src: "/home/{{ansible_user}}/{{working_dir}}/data/{{item}}"
    flat: yes
  loop:
    - zonelist
    - parsed_zonelist

- name: Create zone extraction folders
  file:
    path: "/home/{{ansible_user}}/{{working_dir}}/data/{{item}}"
    state: directory
  loop:
    - "kvsZones"
    - "zones"

- name: Extract zones to data folder
  unarchive:
    dest: "/home/{{ansible_user}}/{{working_dir}}/data/"
    src: "buffer/{{item}}"
    remote_src: no
  loop:
    - kvsZones.tgz
    - zones.tgz
  
- name: Copy Script templates
  template:
    dest: "/home/{{ansible_user}}/{{working_dir}}/tools/{{item.dest}}"
    src: "templates/{{item.src}}"
    mode: 0774
  loop:
    - { src: 'gather_stats.sh.j2', dest: "gather_stats.sh" }
    - { src: 'compute_rate.sh.j2', dest: "compute_rate.sh" }

- name: Start Bind9 server
  shell: "bind9/bin/named/named -c bind9.conf -f -n {{ansible_processor_cores}} &> server.log &"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "bind9"
  
- name: Start Knot2
  shell: knot2/src/knotd -c knot2.conf &> server.log &
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "knot2"

- name: Start Nsd4
  shell: nsd4/nsd -c nsd4.conf -d &> server.log &
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "nsd4"

- name: Start KvsDns and populate
  include_tasks: populate.yml
  when: (orchestrate is defined) and (server != "bind9" and server != "knot2" and server != "nsd4")

- name: Start KvsDns client
  include_tasks: kvsDns.yml
  when: (server != "bind9" and server != "knot2" and server != "nsd4")

- name: Wait for zones to load
  script: "files/wait_zones.sh {{working_dir}}/data/zonelist"