# Go parameters
GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
BINARY_NAME=KvsDns

# Database config
# Select from cassandra,redis,etcd
DB={{server}}
ifeq ($(DB),cassandra)
CLUSTER_IPS="{{server_A}},{{server_B}},{{server_C}}"
else
ifeq ($(DB),redis)
CLUSTER_IPS="{{server_A}}:7001,{{server_A}}:7002,{{server_B}}:7003,{{server_B}}:7004,{{server_C}}:7005,{{server_C}}:7006"
else
CLUSTER_IPS="{{server_A}}:2379,{{server_B}}:2379,{{server_C}}:2379"
endif
endif
CPU_NUMBER="{{ansible_processor_cores}}"
RUN_DB=run_$(DB)
STOP_DB=stop_$(DB)
ANSIBLE_DIR=./scripts/ansible

build:
		@$(GOBUILD) -o $(BINARY_NAME) -v

test:
		@$(GOTEST) -v ./...

clean: $(STOP_DB)
		$(GOCLEAN)
		@rm -f $(BINARY_NAME)

run: $(RUN_DB)
		$(GOBUILD) -o $(BINARY_NAME) -v
		nohup ./$(BINARY_NAME) --clusterIPs $(CLUSTER_IPS) --print --soreuseport $(CPU_NUMBER) --cpu $(CPU_NUMBER) --db $(DB) &

run_standalone:
		$(GOBUILD) -o $(BINARY_NAME) -v
		nohup ./$(BINARY_NAME) --clusterIPs $(CLUSTER_IPS) --print --soreuseport $(CPU_NUMBER) --cpu $(CPU_NUMBER) --db $(DB) &

build_cmd: build_requester build_uploader

build_requester:
		@cd cmd/dnsrequester && $(GOBUILD) -v

build_uploader:
		@cd cmd/queryuploader && $(GOBUILD) -v
		
# Key value store targets using ansible
run_cassandra:
		@cd $(ANSIBLE_DIR) && ansible-playbook --ask-become-pass playbooks/cassandra_up.yml
stop_cassandra:
		@cd $(ANSIBLE_DIR) && ansible-playbook --ask-become-pass playbooks/cassandra_down.yml

run_redis:
		@cd $(ANSIBLE_DIR) && ansible-playbook --ask-become-pass playbooks/redis_up.yml
stop_redis:
		@cd $(ANSIBLE_DIR) && ansible-playbook --ask-become-pass playbooks/redis_down.yml

run_etcd:
		@cd $(ANSIBLE_DIR) && ansible-playbook --ask-become-pass playbooks/etcd_up.yml
stop_etcd:
		@cd $(ANSIBLE_DIR) && ansible-playbook --ask-become-pass playbooks/etcd_down.yml