---

# Backend has been already started by orquestrator

- name: Pass Custom Makefile
  template:
    src: templates/Makefile.j2
    dest: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/Makefile"


- name: Start client at machine
  shell: make run_standalone &
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/"