---

- name: Set facts for play I (random)
  set_fact:
    bindconf: bind9.conf
    knotconf: knot2.conf
    nsdconf: nsd4.conf
    kvsDir: zones
    zlist: zonelist
  when: zones=="random"

- name: Set facts for play II (real)
  set_fact:
    bindconf: bind9r.conf
    knotconf: knot2r.conf
    nsdconf: nsd4r.conf
    kvsDir: kvsZones
    zlist: parsed_zonelist
  when: zones=="real"

- name: Start Bind9 server
  shell: "bind9/bin/named/named -c {{bindconf}} -f -n {{ansible_processor_cores}} &> server.log &"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "bind9"

- name: Start Knot2
  shell: "knot2/src/knotd -c {{knotconf}} &> server.log &"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "knot2"

- name: Start Nsd4
  shell: "nsd4/nsd -c {{nsdconf}} -d &> server.log &"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "nsd4"

- name: Start KvsDns and populate
  include_tasks: populate.yml
  when: (orchestrate is defined) and (server != "bind9" and server != "knot2" and server != "nsd4")

- name: Start KvsDns client
  include_tasks: kvsDns.yml
  when: (server != "bind9" and server != "knot2" and server != "nsd4")

- name: Wait for zones to load
  script: "files/wait_zones.sh data/{{zlist}}"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"