---

# For each backend we must start and then populate
# the respective db

- name: Pass Custom Makefile
  template:
    src: templates/Makefile.j2
    dest: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/Makefile"

- name: Start server backend
  expect:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns"
    command: "make run_{{server}}"
    timeout: null
    responses:
      (?i)password: "{{remote_playbook_password}}"
  ignore_errors: True # When Redis already knows all the nodes

- name: Compile uploader and tools
  command: make build_cmd
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns"

- name: Check for populated.log
  stat:
    path: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/populated-{{server}}-{{zones}}.log"
  register: populated

- name: Upload data folders (may take a while) for Cassandra
  shell: './queryuploader -useZones -dd ../../../data/{{kvsDir}} -clusterIPs "{{server_A}},{{server_B}},{{server_C}}" -db {{server}} > upload.log'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/cmd/queryuploader"
  when: populated.stat.size is not defined and server=="cassandra"

- name: Upload data folders (may take a while) for Redis
  shell: './queryuploader -useZones -dd ../../../data/{{kvsDir}} -clusterIPs {{server_ips}} -db {{server}} > upload.log'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/cmd/queryuploader"
  vars:
    - server_ips: "{{server_A}}:7001,{{server_A}}:7002,{{server_B}}:7003,{{server_B}}:7004,{{server_C}}:7005,{{server_C}}:7006"
  when: populated.stat.size is not defined and server=="redis"

- name: Wait for etcd to load
  wait_for:
    host: "{{item}}"
    port: 2379
    delay: 10
  loop:
    - "{{server_A}}"
    - "{{server_B}}"
    - "{{server_C}}"
  when: server=="etcd"

- name: Upload data folders (may take a while) for Etcd
  shell: './queryuploader -useZones -dd ../../../data/{{kvsDir}} -clusterIPs {{server_ips}} -db {{server}} > upload.log'
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/cmd/queryuploader"
  vars:
    - server_ips: "{{server_A}}:2379,{{server_B}}:2379,{{server_C}}:2379"
  when: populated.stat.size is not defined and server=="etcd"

- name: Register operation
  shell: "echo \"uploaded at $(date '+%Y%m%d-%H-%M')\" > populated-{{server}}-{{zones}}.log"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/"
  when: populated.stat.size is not defined