---

- name: Push config files and zones
  hosts:
    - servers
  roles:
    - prepare
  vars:
    - requester: false
    - server: "{{outer_item.server}}"
    - test: "{{outer_item.test}}"

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{outer_item.server}}"
    - test: "{{outer_item.test}}"

- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - clean
  vars:
    - server: "{{outer_item.server}}"