---

- name: Prepare PCAP files and configs
  hosts:
    - requester
  roles:
    - prepare
  vars:
    - requester: true

- name: Push config files and zones
  hosts:
    - servers
  roles:
    - prepare
  vars:
    - requester: false
    - server: "{{ lookup('env','SERVER')}}"
    - test: "{{ lookup('env','TEST')}}"

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - test: "{{ lookup('env','TEST')}}"

- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - clean
  vars:
    - server: "{{ lookup('env','SERVER')}}"