---

# Random generated zones
- name: Start dns server
  hosts:
    - servers
  roles:
    - start_n_load_zones
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - test: "{{ lookup('env','TEST')}}"
    - zones: random

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - test: "{{ lookup('env','TEST')}}"
    - zones: random
    
- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - clean
  vars:
    - server: "{{ lookup('env','SERVER')}}"

# Scrapped and parsed zones
- name: Start dns server
  hosts:
    - servers
  roles:
    - start_n_load_zones
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - test: "{{ lookup('env','TEST')}}"
    - zones: real

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - test: "{{ lookup('env','TEST')}}"
    - zones: real

- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - clean
  vars:
    - server: "{{ lookup('env','SERVER')}}"