---

- name: Start dns server and get stats
  hosts:
    - servers
  roles:
    - stats
    - start_n_load_zones
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - zones: "{{ lookup('env','ZONES')}}"
    - test_name: "{{ lookup('env','ZONES')}}"
    - op: before

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - zones: "{{ lookup('env','ZONES')}}"
    
- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - stats
    - clean
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - test_name: "{{ lookup('env','ZONES')}}"
    - op: after