---

# Random generated zones
- name: Start dns server and get stats
  hosts:
    - servers
  roles:
    - stats
    - start_n_load_zones
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - zones: random
    - op: before
    - test_name: random

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - zones: random
    
- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - clean
    - stats
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - op: after
    - test_name: random
    
# Scrapped and parsed zones
      
- name: Start dns server and get stats
  hosts:
    - servers
  roles:
    - stats
    - start_n_load_zones
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - zones: real
    - op: before
    - test_name: real

- name: Measure for each server
  hosts:
    - requester
  roles:
    - measure
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - zones: real

- name: Clean and shutdown
  hosts:
    - servers
  roles:
    - clean
    - stats
  vars:
    - server: "{{ lookup('env','SERVER')}}"
    - op: after
    - test_name: real