---

- name: Install requester prerequisites
  hosts:
    - requester
  vars: 
    - requester: true
  roles:
    - install_prerequisites

- name: Install remote servers prerequisites
  hosts:
    - servers
  vars: 
    - requester: false
  roles:
    - install_prerequisites

- name: Compile and install dns servers
  hosts:
    - servers
  roles:
    - install_servers

- name: Get datasets
  hosts:
    - requester
  roles:
    - get_datasets