---

- name: Kill go client on machine
  shell: "kill $(cat KvsDns/kvsDns.pid)"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  ignore_errors: True

- name: Shutdown kvs backend
  expect:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/KvsDns/scripts/ansible"
    command: "ansible-playbook -K playbooks/{{server}}_down.yml"
    timeout: null
    responses:
      (?i)password: "{{remote_playbook_password}}"
  when: (orchestrate is defined) and orchestrate