---

- name: Shutdown bind9 server
  shell: "kill $(cat bind9/named.pid)"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  when: server == "bind9"

- name: Shutdown knot2 server
  shell: "./knot2/src/knotc -c knot2.conf stop"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  when: server == "knot2"

- name: Shutdown nsd4 server
  shell: kill $(cat nsd4/nsd.pid)
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  when: server == "nsd4"

- name: Shutdown KvsDns
  include_tasks: KvsDns.yml
  when: (server != "bind9" and server != "knot2" and server != "nsd4")