---

- name: Shutdown bind9 server
  shell: "kill $(cat bind9/named.pid)"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
  ignore_errors: True
  when: server == "bind9"

- name: Shutdown knot2 server
  shell: "./knot2/src/knotc -c knot2.conf stop"
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  ignore_errors: True
  when: server == "knot2"

- name: Shutdown nsd4 server
  shell: kill $(cat nsd4/nsd.pid)
  args:
    chdir: "/home/{{ansible_user}}/{{working_dir}}"
  ignore_errors: True
  when: server == "nsd4"

- name: Shutdown KvsDns
  include_tasks: KvsDns.yml
  when: (server != "bind9" and server != "knot2" and server != "nsd4")

- name: Ensure that its dead
  wait_for:
    host: "{{ansible_default_ipv4.address}}"
    port: "{{listen_port}}"
    delay: 10
    state: stopped
    timeout: 60
  register: systemstatus
  ignore_errors: True

- name: restart if shutdown failed
  include_tasks: main.yml
  when: "'FAILED' in systemstatus.stderr"