---

- name: Install base packages part 1
  yum:
      name: "{{item}}"
      state: present
  loop:
    - bc
    - tcpreplay
    - perl-core
    - zlib-devel
    - automake
    - libtool
    - autoconf
    - automake
    - make
    - pkgconfig
    - python-pip
    - python3-pip
    - autoconf
    - openssl-devel
    - bind-utils
  become: yes

- name: Copy requirements file
  copy:
      dest: "/home/{{ansible_user}}/{{working_dir}}/requirements.txt"
      src: files/requirements.txt

- name: Install pip requirements
  pip:
    chdir: "/home/{{ansible_user}}/{{working_dir}}/"
    requirements: requirements.txt
    executable: pip3
- name: Install pexpect using pip
  pip:
    name: pexpect
    state: latest
  when: ansible_system == 'Linux'
  
- name: Install base packages part 2
  yum:
    name: "@Development tools"
    state: present
  become: yes
  
- name: Install Bind9 Additional Requirements
  yum:
    name: "{{item}}"
    state: present
  loop:
    - libuv1
    - libcap
    - libtool-ltdl-dev
  become: yes

- name: Install NSD Additional Requirements
  yum:
    name: "{{item}}"
    state: present
  loop:
    - libevent
    - flex
    - bison
  become: yes

- name: Install Knot Additional Requirements
  yum:
    name: "{{item}}"
    state: present
    loop:
      - userspace-rcu-devel 
      - gnutls-devel 
      - libedit-devel
      - lmdb-devel
  become: yes