---

  - name: Install base packages
    apt:
        name: "{{item}}"
        state: present
    loop:
      - bc
      - tcpreplay
      - build-essential
      - checkinstall
      - zlib1g-dev
      - pkg-config
      - python-pip
      - python3-pip
      - autoconf
      - openssl-devel
    become: yes

  - name: Copy requirements file
    copy:
        dest: "/home/{{ansible_user}}/{{working_dir}}/requirements.txt"
        src: files/requirements.txt

  - name: Install pip requirements
    pip:
      chdir: "/home/{{ansible_user}}/{{working_dir}}/"
      requirements: requirements.txt
      executable: pip3

  - name: Install pexpect using pip
    pip:
      name: pexpect
      state: latest
    when: ansible_system == 'Linux'
  
  - name: Install Bind9 Additional Requirements
    yum:
      name: "{{item}}"
      state: present
    loop:
      - libuv1
      - libcap-dev
      - libltdl-dev
    become: yes

  - name: Install NSD Additional Requirements
    yum:
      name: "{{item}}"
      state: present
    loop:
      - libevent-dev
      - flex
      - bison
    become: yes

  - name: Install Knot Additional Requirements
    yum:
      name: "{{item}}"
      state: present
    loop:
      - liburcu-dev
      - libgnutls28-dev
      - libedit-dev
      - liblmdb-dev
    become: yes
  
  