---

  - name: Install base packages
    apt:
        name: "{{item}}"
        state: present
    loop:
      - bc
      - tcpreplay
      - build-essential
      - checkinstall
      - zlib1g-dev
      - pkg-config
      - python-pip
      - python3-pip
    become: yes
  
  - name: Install pip requirements
    pip:
      name:  
        - ply
        - argparse
      state: present 
  
  - name: Install Bind9 Additional Requirements
    yum:
      name: "{{item}}"
      state: present
    loop:
      - libuv1
      - libcap-dev
      - libtltdl-dev
    become: yes

  - name: Install NSD Additional Requirements
    yum:
      name: "{{item}}"
      state: present
    loop:
      - libevent-dev
      - flex
      - bison
    become: yes

  - name: Install Knot Additional Requirements
    yum:
      name: "{{item}}"
      state: present
    loop:
      - liburcu-dev
      - libgnutls28-dev
      - libedit-dev
      - liblmdb-dev
    become: yes
  
  